Revert "pal:Fix StreamUserCounter logic in switchDevice"
This reverts commit 81dcb3b7e9fbaaf096afc07b12f6c6ee4315f7fd.

Reason for revert: <compilation error: FAILED: out/target/product/canoe/obj/DLKM/wcd937x_dlkm.ko_intermediates/wcd937x_dlkm.ko>

Change-Id: I08de1b2f96612300cc9a7f10df68f99856cf6940