Revert "pal: Move from exception handling to regular status check patterns."
This reverts commit 876c9476c4a78590ce7bda3f74f28d473dc8c829.

Reason for revert: <compilation error: FAILED: out/target/product/canoe/obj/DLKM/wcd937x_dlkm.ko_intermediates/wcd937x_dlkm.ko>

Change-Id: Ied3539e748c18b8f117da748ebfc34d47f32416f